import * as core from '@actions/core'

import { SYSTEM_PROMPT } from './../../service/github/copilot/constant'
import { generateContent } from './../../service/github/copilot/generateContent'
import { CopilotQueryBuilder } from './../../service/github/copilot/type'
import { generateCopilotRequest } from './../../service/github/copilot/utils'

export const createPrTitle = async ({ fileChanges }: { fileChanges: string }) => {
  const userPrompt = `${fileChanges}
----------------
Generate a short, easy-to-understand pull request title summarizing the main changes (e.g., style updates, text modifications, bug fixes, new features). Include a prefix [AI-Generated] to indicate it was generated by AI. Return the result in the format: [AI-Generated] <title> (in normal text, not markdown).
`

  const copilotQueryBuilder: CopilotQueryBuilder = {
    copilotRequest: null,
    history: [
      {
        role: 'system',
        content: SYSTEM_PROMPT
      },
      {
        role: 'user',
        content: userPrompt
      }
    ]
  }

  const request = await generateCopilotRequest()

  copilotQueryBuilder.copilotRequest = request

  let result: string | undefined = undefined
  await generateContent(copilotQueryBuilder, (response, done, isError) => {
    if (isError) {
      core.error(response)
      result = undefined
      return
    }

    if (done) {
      core.info(response)
      result = response
      return
    }
  })
  return result
}
